### ISSUE TITLE
How to install this analyzer?

### ISSUE THREAD

**Issue by ghost** [AnthonyDario/rubber-ducky#2]
Hello, we find your work very interesting and would like to reproduce your paper. But the tips of installation are too brief to know the version of OCaml and its dependencies. We are so pleasure if you have some time to help us solve the problems with installation. Thank you very much!

We have followed your tips to install the analyzer with `OCaml-4.10.0` and `round`. But it errored when we executed `make`:

```
$ make
dune clean
dune exec --profile release -- analyzer -test
File "bin/util.ml", line 13, characters 32-39:
13 | let min_ints l = List.fold_left Int.min Int.max_int l ;;
                                     ^^^^^^^
Error: Unbound value Int.min
make: *** [Makefile:25: test] Error 1
```

**Comment by sampollard** [comment]
Thank you for your interest in our project! We haven't documented which exact version of OCaml you need but I tested it and 4.10.0 is too old, you at least need version 4.14. I've found the easiest way to manage this is with opam switches, which are set to a compiler version. The following worked for me on a fresh system with opam 2.1.2.

```
opam switch create 4.14.1
$(opam env --switch=4.14.1)
opam pin add -y round git@github.com:tyabu12/ocaml-round.git
opam install goblint-cil round
make
```

Does that solve your issue?

**Comment by ghost** [comment]
Thank you for your reply, it is now running successfully! Your paper and open-source work have been very inspiring for us. We may consider using other abstract domains to capture floating-point errors and attempt the future work outlined in the paper.

**Comment by AnthonyDario** [comment]
Hi Zoush, I'm glad you're interested in our work. Feel free to email me at adario@uoregon.edu if you have any other questions.
